CREATE DATABASE IF NOT EXISTS LIBRARY_MANAGEMENT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE LIBRARY_MANAGEMENT;

CREATE TABLE IF NOT EXISTS BOOKS(
    `BookId` INT NOT NULL AUTO_INCREMENT,
    `Title` VARCHAR(100) NOT NULL DEFAULT '',
    `Author` VARCHAR(100) NOT NULL DEFAULT '',
    `PageCount` INT NOT NULL DEFAULT 0,
    `BorrowedBy` INT NULL DEFAULT NULL,
    `CreatedAt` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    PRIMARY KEY(`BookId`)
);

CREATE TABLE IF NOT EXISTS BORROWERS(
    `BorrowerId` INT NOT NULL AUTO_INCREMENT,
    `Fullname` VARCHAR(255) NOT NULL DEFAULT '',
    `Email` VARCHAR(255) NOT NULL DEFAULT '', 
    `PhoneNumber` VARCHAR(20) NOT NULL DEFAULT '', 
    `Age` INT NULL DEFAULT NULL,
    `CreatedAt` DATETIME NOT NULL DEFAULT UTC_TIMESTAMP(),
    PRIMARY KEY(`BorrowerId`)
);